var agenda = [
    {
        "nombre":"Inés",
        "telefono":12345,
        "email":[
            "ines@correo.com",
            "info@test.com",
            "test@correo.com"
        ]
    },
    {
        "nombre":"Inés",
        "telefono":12345,
        "email":[
            "ines@correo.com",
            "info@test.com",
            "test@correo.com"
        ]
    }
]
console.log(agenda)